version: 0.2

phases:
  install:
    commands:
      - echo "Installing..."
  build:
    commands:
      - echo "Zipping application files..."
      - zip -r app.zip .

artifacts:
  files:
    - app.zip
